services:
  db:
    container_name: dasboard_empresarial_db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.Backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3333:3333"
    command:
      sh -c "npx prisma db push"
