services:
  db:
    container_name: dasboard_empresarial_db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3333:3333"
      - "3000:3000"